services:
  nextcloud-nginx:
    extends:
      file: ./nginx/docker-compose.yml
      service: nextcloud-nginx
    ports:
      - "8824:8080"
    environment:
      WEBROOT: ${WEBROOT}
    volumes:
      - apps:/app/custom_apps:ro
    depends_on:
      nextcloud-php-fpm:
        condition: service_started
    networks:
      - nxinx-php
      - nginx-collabora

  nextcloud-php-fpm:
    extends:
      file: ./php-fpm/docker-compose.yml
      service: nextcloud-php-fpm
    environment:
      HOST: ${HOST:-localhost:8824}
      PROTOCOL: ${PROTOCOL:-http}
      WEBROOT: ${WEBROOT}
    secrets:
      - nextcloud_db_password
      - nextcloud_admin_password
    volumes:
      - data:/app/data
      - config:/app/config
      - apps:/app/custom_apps
    depends_on:
      nextcloud-db:
        condition: service_started
      collabora:
        condition: service_started
    networks:
      - nxinx-php
      - php-db
      - php-smtp
      - php-collabora

  smtp-relay:
    image: mwaeckerlin/smtp-relay
    networks:
      - php-smtp

  collabora:
    image: collabora/code
    environment:
      server_name: ${HOST:-localhost:8824}
      domain: nextcloud-nginx|localhost
      aliasgroup1: http://nextcloud-nginx:8080,http://localhost:8824
      extra_params: --o:ssl.enable=false --o:ssl.termination=false
    cap_add:
      - MKNOD
    networks:
      - nginx-collabora
      - php-collabora

  nextcloud-db:
    image: mariadb
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/nextcloud_db_password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    secrets:
      - nextcloud_db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - php-db

  access-fix:
    image: mwaeckerlin/allow-write-access
    volumes:
      - data:/app/data
      - config:/app/config
      - apps:/app/custom_apps

secrets:
  nextcloud_db_password:
    environment: NEXTCLOUD_DB_PASSWORD
    #external: true
  nextcloud_admin_password:
    environment: NEXTCLOUD_ADMIN_PASSWORD
    #external: true

volumes:
  data:
  config:
  apps:
  db:


networks:
  nxinx-php:
    driver_opts:
      encrypted: 1
  php-db:
    driver_opts:
      encrypted: 1
  php-smtp:
    driver_opts:
      encrypted: 1
  nginx-collabora:
    driver_opts:
      encrypted: 1
  php-collabora:
    driver_opts:
      encrypted: 1
