services:
  nextcloud-nginx:
    extends:
      file: ./nginx/docker-compose.yml
      service: nextcloud-nginx
    ports:
      - "8824:8080"
    volumes:
      - apps:/app/custom_apps:ro
    environment:
      PHP_FPM_HOST: nextcloud-php-fpm
    depends_on:
      nextcloud-php-fpm:
        condition: service_started
    networks:
      - php-network

  nextcloud-php-fpm:
    extends:
      file: ./php-fpm/docker-compose.yml
      service: nextcloud-php-fpm
    environment:
      PROTOCOL: ${PROTOCOL:-http}
    secrets:
      - nextcloud_db_password
      - nextcloud_admin_password
    volumes:
      - data:/app/data
      - config:/app/config
      - apps:/app/custom_apps
      - ./php-fpm/custom.config.php:/app/config/custom.config.php:ro
    depends_on:
      nextcloud-db:
        condition: service_started
    networks:
      - php-network
      - db-network
      - smtp-network
      - collabora-network

  smtp-relay:
    image: mwaeckerlin/smtp-relay
    networks:
      - smtp-network

  collabora:
    image: collabora/code
    environment:
      aliasgroup1: http://nextcloud-nginx:8080
      extra_params: --o:ssl.enable=false --o:ssl.termination=false
    cap_add:
      - MKNOD
    ports:
      - "9983:9980"
    networks:
      - collabora-network

  nextcloud-db:
    image: mariadb:11.8
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/nextcloud_db_password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    secrets:
      - nextcloud_db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network

  access-fix:
    image: mwaeckerlin/allow-write-access
    volumes:
      - data:/app/data
      - config:/app/config
      - apps:/app/custom_apps

secrets:
  nextcloud_db_password:
    environment: NEXTCLOUD_DB_PASSWORD
    #external: true
  nextcloud_admin_password:
    environment: NEXTCLOUD_ADMIN_PASSWORD
    #external: true

volumes:
  data:
  config:
  apps:
  db:


networks:
  php-network:
    driver_opts:
      encrypted: 1
  db-network:
    driver_opts:
      encrypted: 1
  smtp-network:
    driver_opts:
      encrypted: 1
  collabora-network:
    driver_opts:
      encrypted: 1
