server {
  listen 8080 default_server;
  listen [::]:8080 default_server;
  server_tokens off;
  root ${ROOT};
  index index.php index.html /index.php$request_uri;

  # Error pages
  error_page 500 /502.html;
  error_page 502 /502.html;
  error_page 504 /504.html;
  error_page 404 /404.html;
  error_page 403 /404.html;
  location ~ ^/(502|504|404)\.html { internal; root /etc/nginx/error/$lang; }
  location ~ ^/(502|504|404)\.jpg  { root /etc/nginx/error; }

  # Security headers
  add_header X-Content-Type-Options            "nosniff"           always;
  add_header X-XSS-Protection                  "1; mode=block"     always;
  add_header X-Robots-Tag                      "noindex, nofollow" always;
  add_header X-Download-Options                "noopen"            always;
  add_header X-Permitted-Cross-Domain-Policies "none"              always;
  add_header Referrer-Policy                   "no-referrer"       always;

  # CalDAV / CardDAV auto-redirect
  location ^~ /.well-known {
    location = /.well-known/carddav { return 301 /remote.php/dav/; }
    location = /.well-known/caldav  { return 301 /remote.php/dav/; }
    location /.well-known/acme-challenge  { try_files $uri $uri/ =404; }
    location /.well-known/pki-validation { try_files $uri $uri/ =404; }
    return 301 /index.php$request_uri;
  }

  # Block sensitive directories
  location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/) {
    return 404;
  }
  location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
    return 404;
  }

  include /etc/nginx/locations.d/default.conf;
}
