server {
  listen 8080 default_server;
  listen [::]:8080 default_server;
  root ${ROOT};
  index index.php index.html /index.php$request_uri;
  fastcgi_param modHeadersAvailable true;
  fastcgi_param front_controller_active true;

  # CalDAV / CardDAV auto-redirect
  location ^~ /.well-known {
    location = /.well-known/carddav { return 301 $scheme://$http_host/remote.php/dav/; }
    location = /.well-known/caldav  { return 301 $scheme://$http_host/remote.php/dav/; }
    location /.well-known/acme-challenge  { try_files $uri $uri/ =404; }
    location /.well-known/pki-validation { try_files $uri $uri/ =404; }
    return 301 /index.php$request_uri;
  }

  # Block sensitive directories
  location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/) {
    return 404;
  }
  location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
    return 404;
  }

  # Custom app assets are installed under /app/custom_apps, but some app URLs use /apps/<id>/...
  location ~ ^/apps/([^/]+)/(.+\.(?:css|js|mjs|map|svg|gif|png|jpg|ico|otf|woff2?))$ {
    try_files /custom_apps/$1/$2 $uri /index.php$request_uri;
    expires 6M;
    access_log off;
  }

  include /etc/nginx/locations.d/default.conf;
}
