http:
  routers:
    nextcloud-www:
      entryPoints:
        - websecure
      rule: "HostRegexp(`^www\\..+$`)"
      priority: 200
      middlewares:
        - redirect-www-to-apex
      service: nextcloud
      tls:
        certResolver: letsencrypt

    nextcloud:
      entryPoints:
        - websecure
      rule: "HostRegexp(`^.+$`)"
      priority: 100
      service: nextcloud
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect-www-to-apex:
      redirectRegex:
        regex: "^https://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-nginx:8080"
