  # PHP via FastCGI
  location ~* \.php(?:$|/) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    set $path_info $fastcgi_path_info;
    try_files $fastcgi_script_name =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO       $path_info;
    fastcgi_param HTTPS           on;
    fastcgi_param modHeadersAvailable true;
    fastcgi_param front_controller_active true;
    resolver 127.0.0.11:53 valid=30s;
    fastcgi_pass ${PHP_FPM_HOST}:${PHP_FPM_PORT};
    fastcgi_intercept_errors on;
    fastcgi_request_buffering off;
  }

  # Static assets with long cache
  location ~ \.(?:css|js|svg|gif|png|jpg|ico|woff2?)$ {
    root ${ROOT};
    try_files $uri /index.php$request_uri;
    expires 6M;
    access_log off;
  }

  # Default
  location / {
    root ${ROOT};
    try_files $uri $uri/ /index.php$request_uri;
  }
